### ISSUE TITLE
NGGHandler.java: merging is problematic

### ISSUE THREAD

**Issue by ggianna** [kostagiolasn/NucleosomePatternClassifier#1]
Lines 35-36 (where we merge the graphs) should use a different learning factor.
I propose the use of a counter (e.g. int iCount) to count the number of documents already in the graph.

Then:
tempGraph.mergeGraph(representation.get(i).get(j), 1/(iCount+1));
iCount++;

**Comment by kostagiolasn** [comment]
Added the iCount to count the number of documents already in the graph.
